"""Adicionando taxa_frete corretamente em ItemPedido

Revision ID: 1103adb07415
Revises: e8d7f223ce4c
Create Date: 2025-05-03 23:30:17.509401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1103adb07415'
down_revision = 'e8d7f223ce4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedido', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_endereco',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_pagamento',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)
        batch_op.alter_column('id_estado',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedido', schema=None) as batch_op:
        batch_op.alter_column('id_estado',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id_pagamento',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('id_endereco',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
