"""add id_estado to Livro

Revision ID: 3d5109fc0110
Revises: 16f24b15dcf9
Create Date: 2025-04-22 23:23:33.280962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5109fc0110'
down_revision = '16f24b15dcf9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_estado',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)

    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estado', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('id_usuario', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('id_endereco', sa.String(length=36), nullable=True))
        batch_op.alter_column('id_genero',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.alter_column('id_autor',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_livro_usuario', 'Usuario', ['id_usuario'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_livro_endereco', 'Endereco', ['id_endereco'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_livro_estado', 'Estado', ['id_estado'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Livro', schema=None) as batch_op:
        batch_op.drop_constraint('fk_livro_estado', type_='foreignkey')
        batch_op.drop_constraint('fk_livro_endereco', type_='foreignkey')
        batch_op.drop_constraint('fk_livro_usuario', type_='foreignkey')
        batch_op.alter_column('id_autor',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_genero',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('id_endereco')
        batch_op.drop_column('id_usuario')
        batch_op.drop_column('id_estado')

    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('id_estado',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
