"""Removendo inner join

Revision ID: 4ef468df5fc9
Revises: 60773f3f3b24
Create Date: 2025-05-06 10:42:58.077330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef468df5fc9'
down_revision = '60773f3f3b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Estado', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estado_usuario', type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Estado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key('fk_estado_usuario', 'Usuario', ['id_usuario'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
