"""Adicionando o id de usuário em estado

Revision ID: 60773f3f3b24
Revises: 1103adb07415
Create Date: 2025-05-06 09:54:53.163809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60773f3f3b24'
down_revision = '1103adb07415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Estado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key('fk_estado_usuario', 'Usuario', ['id_usuario'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Estado', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estado_usuario', type_='foreignkey')
        batch_op.drop_column('id_usuario')

    # ### end Alembic commands ###
