"""Modificando a verificacao em endereco

Revision ID: a8ba8e74f943
Revises: 4ef468df5fc9
Create Date: 2025-05-20 09:59:49.896950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ba8e74f943'
down_revision = '4ef468df5fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('rua',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
