"""Modificando a verificacao em endereco1

Revision ID: c4dd8eddac6d
Revises: a8ba8e74f943
Create Date: 2025-05-20 10:20:02.740897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dd8eddac6d'
down_revision = 'a8ba8e74f943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('id_estado',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Endereco', schema=None) as batch_op:
        batch_op.alter_column('id_estado',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
