"""add inner de Estado em Pedido

Revision ID: e8d7f223ce4c
Revises: 2ffd7efe1d47
Create Date: 2025-05-02 15:00:11.881121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d7f223ce4c'
down_revision = '2ffd7efe1d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_estado', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pedido_estado', 'Estado', ['id_estado'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('taxa_frete')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('taxa_frete', sa.FLOAT(), nullable=False))
        batch_op.drop_constraint('fk_pedido_estado', type_='foreignkey')
        batch_op.drop_column('id_estado')

    # ### end Alembic commands ###
